### ISSUE TITLE
OpenCV 3 constants not recognized

### ISSUE THREAD

**Issue by zj88** [intel/caffe#220]
I have latest version of OpenCV. I uncomment OPENCV_VERSION := 3 in Makefile.config and run make all. I get:

CXX src/caffe/layers/lstm_layer.cpp
src/caffe/layers/video_data_layer.cpp: In member function 'virtual void caffe::VideoDataLayer<Dtype>::DataLayerSetUp(const std::vector<caffe::Blob\<Dtype>\*>&, const std::vector<caffe::Blob\<Dtype>*>&)':
src/caffe/layers/video_data_layer.cpp:92:30: error: 'CV_CAP_PROP_FRAME_COUNT' was not declared in this scope
     total_frames_ = cap_.get(CV_CAP_PROP_FRAME_COUNT);
                              ^~~~~~~~~~~~~~~~~~~~~~~
src/caffe/layers/video_data_layer.cpp:97:14: error: 'CV_CAP_PROP_POS_FRAMES' was not declared in this scope
     cap_.set(CV_CAP_PROP_POS_FRAMES, 0);
              ^~~~~~~~~~~~~~~~~~~~~~
make: *** [.build_release/src/caffe/layers/video_data_layer.o] Error 1

Changing to cv::CAP_PROP_FRAME_COUNT fixes, but there are many other constants not recognized. Is Intel Caffe only working with OpenCV 2.4?

**Comment by chuanqi129** [comment]
We also support OpenCV3. What's your build method, make or cmake ? And what's your platform and env? could you try it again after you remove opencv and install it?

**Comment by ftian1** [comment]
We have no problem with OpenCV version being 3. maybe it's your env issue, such as forgetting to set INCLUDE_PATH/LD_LIBRARY_PATH. I would suggest you to use cmake build, which can automatically find corresponding opencv path as soon as you set right CMAKE_INCLUDE_PATH/CMAKE_LIBRARY_PATH.

so close it first.

**Comment by jw-redpanda** [comment]
CV_CAP_PROP_POS_FRAMES and CV_CAP_PROP_FRAME_COUNT are legacy C constant. Use the following instead (removing prefix CV_):
using namespace cv;
// CAP_PROP_POS_FRAMES
// CAP_PROP_FRAME_COUNT

**Comment by catmasteryip** [comment]
> CV_CAP_PROP_POS_FRAMES and CV_CAP_PROP_FRAME_COUNT are legacy C constant. Use the following instead (removing prefix CV_):
> using namespace cv;
> // CAP_PROP_POS_FRAMES
> // CAP_PROP_FRAME_COUNT

The problem persists
